# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f170ebfaf830d83defaab37bb19ac2c21daf73d5404c94b9ad4b59a04e659f210b5c68acfa6bfede994bc0680858e6ebea641d08a7756651b1b90df33c70f8dc

test:
  secret_key_base: e3c89842a5d587c5792b2adab23a3bbba47aa3b8ffcd0318818a385b4b98661ffb06bc14de2b2fcd66107549b3355f8c1559db18aa20c4aa873cad6bcbf1ed0d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
